name: Generate Datas

on:
  schedule:  # Executa a cada 12 horas
    - cron: "0 */12 * * *"

  workflow_dispatch:  # Permite execução manual

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest

    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: BeAndy-cyber
          svg_out_path: dist/github-contribution-grid-snake.svg

      # Faz o push do arquivo gerado para a branch de saída
      - uses: crazy-max/ghaction-github-pages@v3.1.0  # Versão mais recente do GitHub Pages Action
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # Certifique-se de que o secret foi configurado corretamente
